<?php
return [
    'virtual_academic_platform' => 'Plataforma Acadêmica Virtual',
    'enroll_online' => 'Matricule-se em nossos cursos e certificações.',
    'hotel_information' => 'Informações do Hotel',
    'hotel_address' => 'Endereço',
    'hotel_front_desk' => 'Informações da Recepção',
    'hotel_procedures' => 'Reservas com descontos',
    'hotel_click_here' => 'descarregar aqui',
    'speaker_title_1' => 'Orador Principal en Identidad',
    'speaker_desc_1' => 'Nació y creció en Cuba. En 1957 fue ordenado ministro de la Iglesia Metodista y en 1961 se convirtió en la persona más joven en obtener un doctorado en historia teológica de la Universidad de Yale. Durante treinta años el Dr. González enseñó en diversas instituciones teológicas, comenzando con ocho años en el Seminario Evangélico de Puerto Rico (1961-1969). Ha dado cientos de conferencias en Norteamérica, Sudamérica, Europa y Asia. También ha escrito más de cien libros, quizás los más conocidos sean su conjunto de dos volúmenes, Historia del cristianismo, y sus tres volúmenes, Historia del pensamiento cristiano, que han sido traducidos a ocho idiomas. Después de retirarse de la enseñanza a tiempo completo (1977) y del ministerio (1992), ha dedicado su tiempo a investigar, escribir y promover la educación teológica hispana. Como parte de este último, el Dr. González participó en la fundación de la Asociación para la Educación Teológica Hispana (AETH), la Iniciativa Teológica Hispana (HTI) y el Programa de Verano Hispano (HSP). La actividad que más valora y aprecia es asesorar y alentar a latinas, latinos y otros estudiantes minoritarios.',
    'speaker_title_2' => 'Tallerista en Identidad ',
    'speaker_desc_2' => 'El reverendo Dr. Robert Chao Romero es «asiático-latino» y, desde 2005, profesor de Estudios Chicanos y Asiático-Americanos en la UCLA.  Es doctor en Historia Latinoamericana por la UCLA y en Derecho por la Universidad de California en Berkeley. Romero ha publicado más de 30 libros y artículos académicos sobre cuestiones de raza, inmigración, historia, educación y religión, y ha recibido el premio Latina/o Studies book award de la Asociación Internacional de Estudios Latinoamericanos. Su libro más reciente, "Brown Church: Five Centuries of Latina/o Social Justice, Theology, and Identity (2020)", recibió el premio InterVarsity Press Readers´ Choice Award al mejor título académico.  Romero fue becario postdoctoral de la Fundación Ford y del Presidente de la Universidad de California, así como beneficiario de la Beca Sabática para Investigadores del Instituto Louisville.  Robert es también ministro ordenado y organizador comunitario.',
    'speaker_title_3' => 'Tallerista en Identidad y La Mujer ',
    'speaker_desc_3' => 'Pastora Nacional para Ministerios Hispanos de la Iglesia Cristiana (Discípulos de Cristo), es la primera mujer elegida a este cargo. Además, la Pastora Lori es plantadora de iglesias, autora, oradora y motivadora. La Pastora Tapia sirve con una pasión por compartir a Jesús de manera relevante, por empoderar a otros ayudándoles a crecer en su llamado y propósito, y por construir y mantener relaciones sólidas, auténticas y fieles que avanzan el reino entre nosotros. Profundamente arraigada en su ser es la adoración a través de la música como cantautora y adoradora. La Rev. Tapia recibió su Maestría en Divinidad de Claremont School of Theology, y fue otorgada con el Premio a la Predicación de la Iglesia del Buen Pastor y el Premio de la Fundación del Seminario de Discípulos. La Pastora cuenta con más de 25 años de experiencia en la administración y desarrollo de programas comunitarios, familiares, y de servicios sociales. La Pastora Lori, quien nació en la frontera de Arizona y México, es orgullosa de su cultura México Americana y ha trabajado a nivel binacional para crear fronteras saludables y desarrollar programas mejorando la calidad de vida en áreas de salud, jóvenes y familias.',
    'speaker_title_4' => 'Tallerista en Piezas perdidas: El latino, el inmigrante, el trauma, la identidad y la Iglesia.',
    'speaker_desc_4' => 'El Dr. Harris tiene una licenciatura en psicología de la Universidad de California, Irvine, así como una maestría y un doctorado en psicología clínica de la Universidad Estatal de Washington. Después de completar una pasantía clínica en la UCLA, realizó estudios posdoctorales en la Universidad de Cornell. El Dr. Harris es miembro clínico y anteriormente se desempeñó como Oficial del Programa de Becas para Minorías de la Asociación Estadounidense de Psicología. En este cargo, gestionó y redactó subvenciones de varias agencias federales, incluyendo el NIMH, NIA, SAMHSA, CSAP, CSAT, entre otras. También es un exitoso redactor de subvenciones para fundaciones, habiendo obtenido más de una docena de subvenciones de organizaciones importantes como la Fundación Lilly, la Fundación de la Familia Kern, la Fundación Oddo y la Fundación López.
El Dr. Harris ha ocupado cargos docentes con permanencia en la Universidad Vanguard y la Universidad Bethany, además de enseñar y ser profesor adjunto en instituciones como la Universidad Estatal de Washington, la Universidad Pepperdine y la Facultad de Medicina de la UCI. Mantiene una práctica de consejería pastoral, ofreciendo servicios gratuitos a pastores y sus familias. Durante los últimos seis años, el Dr. Harris ha sido miembro del Comité Nacional de Salud Mental de las Asambleas de Dios (2018-presente) y ha sido profesor adjunto en el Seminario Azusa Pacific durante la última década, enfocándose en la formación en salud mental para pastores y líderes eclesiásticos. Ordenado ministro de las Asambleas de Dios, el Dr. Harris también ocupa los cargos de Comisionado COA de ABHE y Presidente/Director Ejecutivo del LABI College en La Puente, California.',
    'speaker_title_5' => 'Tallerista Identidad y la predicación',
    'speaker_desc_5' => 'El Rev. Dr. David Vásquez-Levy es Presidente del seminario y centro de liderazgo Pacific School of Religion (PSR), localizado en Berkeley, California. Él es un pastor comprometido, un líder reconocido a nivel nacional y un orador bien solicitado. El liderazgo del Dr. Vásquez-Levy ha sido forjado en la intersección de la fe, la educación superior y el cambio social, guiando su trabajo en la preparación de líderes teológicos y espiritualmente arraigados para la transformación social. Creció en Guatemala en un hogar interreligioso, judío y cristiano, y ha vivido, estudiado y trabajado en cuatro países. Por su propia experiencia, trabajo académico y vocación religiosa, le apasiona servir con aquellos que están “en movimiento”: congregaciones en transición, estudiantes que disciernen y viven sus llamados, así como migrantes. 

Fue uno de los fundadores de La Colectiva, un grupo de ejecutivos Hispanos de la Asociación de Escuelas Teológicas (ATS), y es un miembro del grupo ejecutivo de la red de universidades de AshokaU. También es presidente de la junta de Church World Service, uno de los programas ecuménicos de desarrollo global y migración más grandes del mundo, y miembro de la junta directiva de la Unión Graduada Teológica (GTU). Vásquez-Levy contribuye regularmente una perspectiva de fe a la conversación nacional sobre inmigración, incluyendo hablar en una sesión informativa del Congreso de Estados Unidos, consultas de inmigración con la Casa Blanca de Obama y Biden, participar en una serie de conversaciones públicas con varios fiscales estatales en un esfuerzo por replantear nuestra conversación nacional sobre inmigración.  Ha trabajado como consultor en varios documentales sobre inmigración, trabajo y derechos humanos y es autor de varias publicaciones que exploran historias de migración en textos sagrados y en la vida de las personas.',
    'speaker_title_6' => 'Tallerista Identidad y Acompañamiento Pastoral',
    'speaker_desc_6' => 'Guesnerth Josué Perea es Director Ejecutivo del foro afrolatin@, Co-Curador del Proyecto de Teología Afrolatina, Productor Ejecutivo del documental "Faith in Blackness: An Exploration of AfroLatine Spirituality", y copresentador del podcast "Majestad Prieta". Sus escritos sobre la AfroLatinidad han formado parte de varias publicaciones, entre las que se incluyen ¡Dejad Hablar al Espíritu! Cultural Journeys through the African Diaspora, la Revista de Estudios Colombianos, y más recientemente Engaging Religion, una revista digital de la Universidad de Indiana. Josué fue nombrado en una ocasión por el periódico amNewYork como uno de los cinco colombianos que "dejan huella" en la ciudad de Nueva York.',
    'speaker_title_7' => 'Tallerista Identidad y Young Lideres',
    'speaker_desc_7' => 'El Dr. Wilmer Estrada Carrasquillo, oriundo de Puerto Rico, es profesor asociado de evangelismo E. Stanley Jones en el Seminario Teológico de Asbury. Wilmer no solo aporta su experiencia en educación superior, sino que también ha servido a la iglesia como pastor y administrador.


Wilmer ha escrito dos libros: Hacia una eclesiología hispano-latina: Una respuesta a la McDonaldización (Center for Latino Studies Press, 2018) y Beyond the Temple: Pentecostal Spirituality as a Lived Ecclesiology (CPT Press: Cleveland, TN. Book, 2021). Ambas monografías analizan la presencia pública de la iglesia y su llamado a encarnar el evangelio en sus contextos. Además, fue coautor de The Church and Migration con Daniel Montañez, publicó artículos de revistas, entradas de enciclopedias y capítulos de libros sobre espiritualidad pentecostal, misión y evangelización, la intersección entre fe y cultura, teología latina y la relación entre el pentecostalismo y el movimiento wesleyano.


Wilmer vive en Cleveland, Tennessee, con Laura y sus tres hijas: Kalani, Mía y Valeria, y su hijo, Anthony.',
    'speaker_title_8' => 'Tallerista Identidad y Migración ',
    'speaker_desc_8' => 'El Dr. Oscar García-Johnson es un reconocido académico, experimentado líder pastoral e innovador en la educación teológica autóctona enfocada en los mileniales y las comunidades indígenas y emergentes del Sur Global. Su destacado historial incluye roles clave como director general de Diversidad, Equidad e Inclusión (2021-2023) y Decano Académico del Centro para el Estudio de la Iglesia y Comunidad Hispana (2015-2021) del Seminario Teológico Fuller. Con una experiencia docente de 25 años, en la actualidad, enriquece la comunidad del Seminario Fuller como Profesor de Teología y Estudios Decoloniales.

La variada formación educativa del Dr. García-Johnson abarca un Doctorado Filosófico en Teología y una Maestría en Estudios Bíblicos del Seminario Fuller, una licenciatura en Filosofía y Religión de la Universidad de La Verne, estudios avanzados de Ingeniería Eléctrica de la Universidad Nacional Autónoma de Honduras y cursos de Banca Hipotecaria (USA). Oriundo de Honduras y ubicado en EE.UU. por más de treinta años, el Dr. García-Johnson se auto-posiciona como erudito de la diáspora latina. Y desde esa identidad transfronteriza forja sus perspectivas teológicas, interculturales, misionales e interestatales. Sus obras influyentes incluyen la nueva serie de siete volúmenes "Teología del Nuevo Mundo" (CLIE 2022 —) y exploraciones incisivas de epistemologías decoloniales y hermenéutica transoccidental en Spirit Outside the Gate (IVP Academic 2019), Theology Without Borders (co-escritor, Baker Academic 2015) y Conversaciones Teológicas del Sur Global Americano (co-editor, Puertas Abiertas/Wipf & Stock, 2016). Su propuesta de una teología práctica transnacional arraigada en el Espíritu para el pastor urbano en The Mestizo/a Community of the Spirit (Pickwick/Wipf & Stock 2009) continúa proporcionando una base para la imaginación eclesial desde los márgenes en el Norte Global.

Más allá de la academia, el Dr. García-Johnson aprovecha su amplia experiencia en liderazgo denominacional y plantación de iglesias para brindar perspicaces perspectivas sobre la dinámica del ministerio multilingüe e intercultural contemporáneo. Sus colaboraciones internacionales han avanzado en la educación teológica en América Latina, África, el Oriente Medio, Asia y los Estados Unidos.

Como gestor de enfoques decoloniales, el Dr. García-Johnson fomenta un entorno de aprendizaje enriquecido e intergeneracional que abraza las perspicacias del liderazgo emergente y promueve un discurso teológico provocador, desvictimizante e integral.',
    'speaker_title_9' => 'Palestrante Principal sobre Trauma',
    'speaker_desc_9' => 'A Rev.ª Dra. Alma Tinoco Ruiz é uma acadêmica, pastora e educadora dedicada aos campos da homilética, evangelização e ministério hispânico/latino. Sua paixão abrange a educação teológica, a defesa da justiça e a interseção entre pregação, cuidado pastoral e evangelização.',
    'speaker_desc_9a' => 'A Rev.ª Dra. Tinoco Ruiz é uma teóloga prática cujo trabalho foca na interseção entre homilética, cuidado pastoral e evangelização. Ao longo de seu ministério, ela observou que a maioria dos pregadores não está adequadamente preparada para lidar com feridas traumáticas sofridas por comunidades marginalizadas e oprimidas. Em contraste, ela encontra nos sermões de São Óscar Romero uma resposta profunda aos traumas vividos pelo povo marginalizado de El Salvador durante seu tempo como arcebispo de San Salvador (1977–1980). Influenciada pela pregação de San Romero, a professora Tinoco Ruiz explora como os pregadores podem abordar eficazmente os traumas vividos por comunidades marginalizadas, especialmente imigrantes latino-americanos indocumentados nos Estados Unidos. Ela concluiu sua tese de doutorado intitulada: "A estrutura teológica, hermenêutica e pastoral de Óscar Romero para pregar a comunidades traumatizadas." Suas publicações incluem artigos no International Journal of Homiletics, Predicación con Impacto, The Christian Century e na revista DIVINITY da Duke Divinity School. Ela foi reconhecida com bolsas pela Foundation for Evangelism (2016), Forum for Theological Exploration (2019) e Hispanic Theological Initiative (2020). É ministra ordenada da Igreja Metodista Unida.',

    'speaker_title_harold' => 'Oficina Trauma e Infância',
    'speaker_desc_harold' => 'Dr. Harold Segura é colombiano e Diretor do Departamento de Fé e Desenvolvimento da Visão Mundial para América Latina e Caribe. Professor universitário e teólogo. Ex-reitor do Seminário Teológico Batista Internacional. Doutor em teologia pela Pontifícia Universidade Javeriana da Colômbia e doutorando em Filosofia pela Universidade Nacional da Costa Rica. Autor de livros sobre espiritualidade cristã, teologia da infância, liderança e missão da igreja. Suas obras recentes incluem: Teologia em tempos de TikTok, O Evangelho em poucas palavras, e Pinceladas do Evangelho.',

    'speaker_title_yenny' => 'Oficina Mulher e Trauma',
    'speaker_desc_yenny' => 'Yenny Delgado é doutoranda em Psicologia da Religião na Universidade de Lausanne, Suíça. É acadêmica e ativista comprometida com a teologia decolonial, libertadora e feminista/mujerista. Nascida no Peru, atua em pesquisa, educação e ação social em diversos países. Possui formação em Psicologia (Universidade Federico Villarreal), Teologia (Universidade Bíblica Latino-americana), Cooperação para o Desenvolvimento (Universidade Jaume I), e Teologia Pública (Seminário Teológico Wesley). Líder religiosa e membro da Igreja Presbiteriana dos EUA, fundou a Pública Theology e coordena a rede Mujeres Haciendo Teología em Abya Yala. Seu trabalho contribui para uma teologia contextualizada voltada à justiça social e equidade de gênero.',

    'speaker_title_pablo' => 'Oficina Trauma e Institutos Bíblicos',
    'speaker_desc_pablo' => 'Pablo Anabalon é diretor executivo de divisões regionais em Los Angeles pela Pacific Clinics. Psicólogo formado pela Universidade do Chile e doutor pela Universidade de Biola, com residência na Universidade de Boston. Possui mais de 25 anos de experiência clínica e administrativa, liderando comitês voltados à diversidade cultural, serviços latinos e saúde mental.',

    'speaker_title_andrea' => 'Oficina Trauma e Jovens Líderes',
    'speaker_desc_andrea' => 'Dra. Drea Kauffman Canales, do Havaí, atua há 20 anos em liderança pastoral na comunidade latina de Los Angeles. Pastora em La Fuente Ministries e psicóloga clínica licenciada, tem formação em Psicologia Clínica (Fuller), Estudos Familiares, Interculturais e Teologia. Atua como terapeuta bilíngue com foco em trauma, luto e crescimento relacional. É também professora afiliada no Seminário Teológico Fuller.',

    'speaker_title_salvatierra' => 'Oficina Trauma e Migração',
    'speaker_desc_salvatierra' => 'Reverenda Dra. Salvatierra é Decana Acadêmica do Centro Latino e professora associada de Missão e Transformação Global no Seminário Teológico Fuller. Especialista em estudos migratórios, tem mais de 40 anos de atuação ministerial com imigrantes e iniciativas de justiça social na igreja.',

    'speaker_title_malave' => 'A Voz da Igreja – a Consciência do Estado',
    'speaker_desc_malave' => 'O reverendo Carlos L. Malave é presidente da Rede Nacional Cristã Latina (LCNN). A LCNN é uma ampla rede cristã latina nos Estados Unidos que inclui líderes pentecostais, evangélicos, católicos e de igrejas tradicionais. Ele também atua como pastor das igrejas Appomattox Court House e New Concord Presbyterian, na Virgínia. Por nove anos, foi diretor executivo da Christian Churches Together in the USA (CCT). Carlos é apaixonado por defesa dos direitos, unidade e amor.',

    'speaker_title_montanez' => 'Oficina Técnica e Jovens Líderes',
    'speaker_desc_montanez' => 'Daniel Montañez é doutorando em teologia, ética e filosofia pela Faculdade de Teologia da Universidade de Boston. É fundador e diretor da Mygration Christian Conference, uma conferência anual que explora como as histórias de migração nas Escrituras cristãs podem dialogar com as histórias de imigrantes nos dias atuais. Também é diretor nacional da Iniciativa para a Crise Migratória da Igreja de Deus (Cleveland, TN), que prepara pastores e líderes com fundamentos bíblicos, teológicos e pastorais para responder proativamente às necessidades das comunidades imigrantes. Já integrou a diretoria da AETH e atualmente participa da liderança da NaLEC, Agência ALPHA e do Centro de Estudos Bíblicos e Ministério (CEBM). É coeditor do livro "A Igreja e a Migração: Uma Visão Teológica para o Povo de Deus" e dedica-se à interseção entre Igreja, academia e vida pública.',

    'speaker_title_fraiser' => 'Oficina Técnica e Espiritualidade',
    'speaker_desc_fraiser' => 'A Rev.ª Dra. Elizabeth Conde Frazier é teóloga prática e pastora ordenada das Igrejas Batistas Americanas, com mais de dez anos de experiência pastoral. Fundou o Programa de Ministérios Hispânicos e Latino-Americanos Orlando E. Costas na Escola Teológica Andover Newton e atuou como professora titular de educação religiosa em Claremont School of Theology. Também foi reitora acadêmica e vice-presidente de educação no Esperanza College da Eastern University, além de diretora da AETH. Entre suas publicações estão: "Atando Cabos", "Latina Evangélicas", "A Many Colored Kingdom", "Institutos Bíblicos Hispanos", "Escuchando a los niños" e diversos capítulos sobre teologia prática e educação religiosa. Possui Ph.D. pela Boston College, M.Div. pelo Seminário Teológico Batista de Eastern e bacharelado pelo Brooklyn College da City University of New York.',

    'speaker_title_viera' => 'Oficina Institutos Bíblicos e Técnica',
    'speaker_desc_viera' => 'O Rev. Dr. Javier A. Viera é presidente do Seminário Teológico Evangélico Garrett, onde também atua como professor de Educação e Liderança. Desde 2021, lidera a instituição com novo plano estratégico, revisão curricular, processos de acreditação, programas inovadores e aumento de matrículas. Foi reitor da Drew University School of Theology (2014–2020), onde também foi vice-reitor e professor de Teologia Pastoral. Teórico e historiador da educação, sua pesquisa se concentra na aprendizagem de adultos e epistemologias decoloniais latino-americanas. Serviu por duas décadas em ministérios universitários e congregacionais. Graduado pelas universidades Florida Southern, Duke, Yale e Columbia, é natural de San Juan, Porto Rico.',

    'speaker_title_caballero' => 'Oficina Migração e Técnica',
    'speaker_desc_caballero' => 'O Dr. Caballero é atualmente presidente executivo do Centro Hispano de Estudos Teológicos (CHET) e presidente do conselho da AETH. Líder na educação teológica latina e advogado, tem vasta experiência ministerial e lidera iniciativas significativas no meio educacional e comunitário latino. De origem mexicana, hondurenha, salvadorenha e libanesa, vem de uma família de ministros evangélicos. É graduado pela UCLA, possui mestrado em estudos jurídicos (Trinity International University), em educação religiosa (West Coast Baptist College) e doutorado em Direito (Appalachian School of Law).',

    'speaker_title_lugo' => 'Oficina Mulher e Pregação',
    'speaker_desc_lugo' => 'A Dra. Jessica Lugo é pastora, educadora e administradora. Nascida em San Juan, Porto Rico, é Ministra Ordenada das Igrejas Batistas Americanas e integra o corpo pastoral das Igrejas Batistas de Porto Rico. Também colabora com outras tradições de fé. É professora de História do Cristianismo, Novo Testamento e Evangelismo em cursos de pós-graduação, além de atuar como docente adjunta em vários Institutos Bíblicos e em cursos de Administração. É diretora executiva da AETH, colaborando com teólogos e historiadores para fortalecer a educação teológica. Possui Doutorado em Ministério (Liberty University), M.Div. (Seminário Evangélico de Porto Rico), Mestrado em Administração com foco em Marketing e Bacharelado em Contabilidade (Universidade Ana G. Méndez). Para ela, o maior título é o de servir.',

    'speaker_title_merlo' => 'Oficina Pregação e Plantadores de Igrejas',
    'speaker_desc_merlo' => 'O Dr. Oscar Merlo é líder visionário, educador e estrategista dedicado à formação de líderes pastorais hispânicos. Como gerente de Pregação Transformadora da AETH e co-diretor da Iniciativa Nacional para Fortalecer Líderes Pastorais Hispanos (NISHPLC), lidera o futuro do ministério latino nos EUA. Também é professor assistente de Missiologia no Centro Latino do Seminário Fuller. Possui Ph.D. em Estudos Interculturais (Fuller) e formações em liderança, negócios, teologia, psicologia e filosofia. Nascido em Honduras e criado na Califórnia, sua trajetória como imigrante o inspira na busca por justiça, espiritualidade e transformação. Atuou em mais de 40 países e lidera iniciativas educacionais com alcance global. Nos momentos livres, viaja com a família e cultiva seu jardim.',

    'speaker_title_rocha' => 'Oficina Pregação e Plantadores de Igrejas',
    'speaker_desc_rocha' => 'O Pastor Robert Rocha e sua esposa Liz são os fundadores da Voz Church em Ontario, Califórnia — igreja que nasceu em 2018 com a visão de restaurar lares com base em Malaquias 4:6. Seu ministério é centrado na graça que cura, restaura e capacita pelo Espírito Santo. Lideram uma comunidade multigeracional e multiétnica onde famílias são discipuladas e transformadas. A Voz Church é uma das igrejas de crescimento mais rápido em Los Angeles.',



];
