<?php
return [
    'speaker_title_1' => 'Identity Keynote Speaker',
    'speaker_desc_1' => 'Dr. Justo L. González was born and raised in Cuba. In 1957 he was ordained as a minister within the Methodist Church, and in 1961 he became the youngest person to earn a doctorate in theological history from Yale University. For thirty years Dr. González taught at various theological institutions, beginning with eight years at the Seminario Evangélico de Puerto Rico (1961-1969). He has given hundreds of lectures in North America, South America, Europe, and Asia. He has also written over one hundred books, perhaps the best known of which are his two-volume set, History of Christianity, and his three volumes, History of Christian Thought, which have been translated into eight languages. After retiring from full-time teaching (1977) and the ministry (1992), he has dedicated his time to research, writing, and promoting Hispanic theological education. As part of the latter, Dr. González was involved in the founding of the Asociación para la Educación Teológica Hispana (AETH), the Hispanic Theological Initiative (HTI), and the Hispanic Summer Program (HSP). The activity he most values and appreciates is mentoring and encouraging Latinas and Latinos and other minority students.',
    'speaker_title_2' => 'Identity Workshop',
    'speaker_desc_2' => 'Rev. Dr. Robert Chao Romero is "Asian-Latino," and has been a professor of Chicana/o Studies and Asian American Studies at UCLA since 2005.  He received his Ph.D. from UCLA in Latin American History and his Juris Doctor from U.C. Berkeley. Romero has published more than 30 academic books and articles on issues of race, immigration, history, education, and religion, and received the Latina/o Studies book award from the international Latin American Studies Association. His recent book, “Brown Church: Five Centuries of Latina/o Social Justice, Theology, and Identity (2020),” received the InterVarsity Press Readers’ Choice Award for best academic title.  Romero is a former Ford Foundation and U.C. President´s Postdoctoral Fellow, as well as a recipient of the Louisville Institute´s Sabbatical Grant for Researchers.  Robert is also an ordained minister and community organizer. ',
    'speaker_title_3' => 'Identity and Women Workshop',
    'speaker_desc_3' => 'National Pastor for Hispanic Ministries of the Christian Church (Disciples of Christ), she is the first woman to be elected to this position. In addition, Pastor Lori is a church planter, author, speaker and motivational speaker. Pastor Tapia serves with a passion for sharing Jesus in relevant ways, for empowering others by helping them grow in their calling and purpose, and for building and maintaining strong, authentic and faithful relationships that advance the kingdom among us. Deeply rooted in her being is worship through music as a singer-songwriter and worshipper. Rev. Tapia received her Master of Divinity degree from Claremont School of Theology, and was awarded the Church of the Good Shepherd Preaching Award and the Disciples Seminary Foundation Award. Pastor Lori has more than 25 years of experience in the administration and development of community, family, and social service programs. Pastor Lori, who was born on the border of Arizona and Mexico, is proud of her Mexican American culture and has worked bi-nationally to create healthy borders and develop programs to improve the quality of life in the areas of health, youth and families.',
    'speaker_title_4' => 'Missing Pieces: The Latino, Inmigrant, Trauma, Identity and the Church Workshop',
    'speaker_desc_4' => 'Dr. Harris holds a bachelor´s degree in psychology from the University of California, Irvine, as well as a master´s degree and doctorate in clinical psychology from Washington State University. Following a clinical internship at UCLA, he pursued postdoctoral work at Cornell University. Dr. Harris is a clinical fellow and formerly served as Program Officer for the American Psychological Association´s Minority Scholarship Program. In this capacity, he managed and wrote grants from various federal agencies, including NIMH, NIA, SAMHSA, CSAP, CSAT, and others. He is also an accomplished grant writer for foundations, having secured more than a dozen grants from major organizations like the Lilly Endowment, Kern Family Foundation, Oddo Foundation, and Lopez Foundation.
    Dr. Harris has held tenured faculty positions at Vanguard University and Bethany University, in addition to teaching and serving as adjunct faculty at institutions such as Washington State University, Pepperdine University, and UCI School of Medicine. He maintains a pastoral counseling practice, offering complimentary services to pastors and their families. Over the past six years, Dr. Harris has been a member of the Assemblies of God National Mental Health Committee (2018-present) and has served as an adjunct professor at Azusa Pacific Seminary for the past decade, focusing on mental health training for pastors and church leaders. An ordained minister of the Assemblies of God, Dr. Harris also holds positions as COA Commissioner of ABHE and President/CEO of LABI College in La Puente, California.',
    'speaker_title_5' => 'Identity and Preaching Workshop',
    'speaker_desc_5' => 'Rev. Dr. David Vásquez-Levy serves as President of Pacific School of Religion in Berkeley, California –a seminary and center for social justice that prepares spiritually rooted leaders to create a world where all can thrive.  A committed pastor, nationally recognized leader, and a sought after speaker, he leads at the intersection of faith, higher education, and social change. Born and raised in a Christian-Jewish household in Guatemala, he has lived in four countries. His experience, research, and passion guide his work with those “on the move”: congregations in transition, students discerning their callings, and immigrants. 
    He co-founded La Colectiva, a group of Latino/a executive leaders at ATS schools, and is a member of the executive leaders group of AshokaU campus network.  He also serves on the board of the Graduate Theological Union and is Chair of the board of Church World Service, one of the largest ecumenical development agencies in the world.  Vásquez-Levy regularly contributes a faith perspective to the national conversation on immigration, including speaking at a congressional briefing, immigration consultations with the both the Obama and the Biden White House, engaging in a series of public conversation with various State Attorneys across the country in an effort to reframe our national conversation about immigration.  He has consulted on a number of documentaries on immigration, labor, and human rights and is the author of various publications that explore migration stories in sacred texts and in people´s lives. ',
    'speaker_title_6' => 'Identity and Pastoral Advocacy Workshop',
    'speaker_desc_6' => 'Guesnerth Josué Perea is Executive Director of the afrolatin@ forum, Co-Curator of the AfoLatine Theology Project, Executive Producer of the documentary "Faith in Blackness: An Exploration of AfroLatine Spirituality", and Co-Host of the podcast "Majestad Prieta". His writings on AfroLatinidad have been part of various publications including Let Spirit Speak! Cultural Journeys through the African Diaspora, the Revista de Estudios Colombianos, and most recently Engaging Religion, a digital journal by Indiana University. Josué was once named by the newspaper amNewYork as one of five Colombians "making a mark" in New York City. ',
    'speaker_title_7' => 'Young Lideres and Identity Workshop',
    'speaker_desc_7' => 'Dr. Wilmer Estrada Carrasquillo, a native Puerto Rican, is the E. Stanley Jones Associate Professor of Evangelism at the Asbury Theological Seminary. Wilmer not only brings his experience in higher education but has also served the church as pastor and administrator.
Wilmer has written two books: Hacia una eclesiología Hispana-Latina: Una respuesta a la McDonaldización (Center for Latino Studies Press, 2018) and Beyond the Temple: Pentecostal Spirituality as a Lived Ecclesiology (CPT Press: Cleveland, TN. Book, 2021). Both monographs look at the church’s public presence and her calling to embody the gospel in its contexts. Furthermore, he co-authored The Church and Migration with Daniel Montañez, published journal articles, encyclopedia entries, and book chapters on Pentecostal spirituality, mission and evangelism, the intersection between faith and culture, Latina Theology, and the relationship between Pentecostalism and the Wesleyan movement.
Wilmer lives in Cleveland, TN, with Laura and their three daughters –Kalani, Mía, and Valeria, and their son, Anthony.',
    'speaker_title_8' => 'Identity and Migration Workshop',
    'speaker_desc_8' => 'Dr. Oscar Garcia-Johnson is a renowned scholar, experienced pastoral leader and innovator in indigenous theological education focused on millennials and indigenous and emerging communities in the Global South. His outstanding track record includes key roles as CEO of Diversity, Equity and Inclusion (2021-2023) and Academic Dean of the Center for the Study of the Hispanic Church and Community (2015-2021) at Fuller Theological Seminary. With 25 years of teaching experience, he currently enriches the Fuller Seminary community as Professor of Theology and Decolonial Studies.',
    'speaker_desc_8a' =>
        'Dr. García-Johnson´s varied educational background includes a Doctorate in Philosophical Theology and a Masters in Biblical Studies from Fuller Seminary, a B.A. in Philosophy and Religion from the University of La Verne, advanced studies in Electrical Engineering from the National Autonomous University of Honduras, and courses in Mortgage Banking (USA). A native of Honduras and based in the U.S. for over thirty years, Dr. Garcia-Johnson positions himself as a scholar of the Latino diaspora. And from that cross-border identity he forges his theological, cross-cultural, missional and interstate perspectives. His influential works include the new seven-volume series “New World Theology” (CLIE 2022 -) and incisive explorations of decolonial epistemologies and transwestern hermeneutics in Spirit Outside the Gate (IVP Academic 2019), Theology Without Borders (co-writer, BakerAcademic 2015) and Theological Conversations from the American Global South (co-editor, Open Doors/Wipf & Stock, 2016). His proposal for a Spirit-rooted transnational practical theology for the urban pastor in The Mestizo/a Community of the Spirit (Pickwick/Wipf&Stock 2009) continues to provide a basis for ecclesial imagination from the margins in the Global North.',
    'speaker_desc_8b' => 'Beyond the academy, Dr. Garcia-Johnson draws on his extensive experience in denominational leadership and church planting to provide insightful perspectives on the dynamics of contemporary multilingual and cross-cultural ministry. His international collaborations have advanced theological education in Latin America, Africa, the Middle East, Asia and the United States.',
    'speaker_desc_8c' => 'As a manager of decolonial approaches, Dr. Garcia-Johnson fosters an enriched, intergenerational learning environment that embraces emerging leadership insights and promotes provocative, de-victimizing and holistic theological discourse.',

];