<?php
return [
    'speaker_title_1' => 'Identity Keynote Speaker',
    'speaker_desc_1' => 'Dr. Justo L. González was born and raised in Cuba. In 1957 he was ordained as a minister within the Methodist Church, and in 1961 he became the youngest person to earn a doctorate in theological history from Yale University. For thirty years Dr. González taught at various theological institutions, beginning with eight years at the Seminario Evangélico de Puerto Rico (1961-1969). He has given hundreds of lectures in North America, South America, Europe, and Asia. He has also written over one hundred books, perhaps the best known of which are his two-volume set, History of Christianity, and his three volumes, History of Christian Thought, which have been translated into eight languages. After retiring from full-time teaching (1977) and the ministry (1992), he has dedicated his time to research, writing, and promoting Hispanic theological education. As part of the latter, Dr. González was involved in the founding of the Asociación para la Educación Teológica Hispana (AETH), the Hispanic Theological Initiative (HTI), and the Hispanic Summer Program (HSP). The activity he most values and appreciates is mentoring and encouraging Latinas and Latinos and other minority students.',
    'speaker_title_2' => 'Identity Workshop',
    'speaker_desc_2' => 'Rev. Dr. Robert Chao Romero is "Asian-Latino," and has been a professor of Chicana/o Studies and Asian American Studies at UCLA since 2005.  He received his Ph.D. from UCLA in Latin American History and his Juris Doctor from U.C. Berkeley. Romero has published more than 30 academic books and articles on issues of race, immigration, history, education, and religion, and received the Latina/o Studies book award from the international Latin American Studies Association. His recent book, “Brown Church: Five Centuries of Latina/o Social Justice, Theology, and Identity (2020),” received the InterVarsity Press Readers’ Choice Award for best academic title.  Romero is a former Ford Foundation and U.C. President´s Postdoctoral Fellow, as well as a recipient of the Louisville Institute´s Sabbatical Grant for Researchers.  Robert is also an ordained minister and community organizer. ',
    'speaker_title_3' => 'Identity and Women Workshop',
    'speaker_desc_3' => 'National Pastor for Hispanic Ministries of the Christian Church (Disciples of Christ), she is the first woman to be elected to this position. In addition, Pastor Lori is a church planter, author, speaker and motivational speaker. Pastor Tapia serves with a passion for sharing Jesus in relevant ways, for empowering others by helping them grow in their calling and purpose, and for building and maintaining strong, authentic and faithful relationships that advance the kingdom among us. Deeply rooted in her being is worship through music as a singer-songwriter and worshipper. Rev. Tapia received her Master of Divinity degree from Claremont School of Theology, and was awarded the Church of the Good Shepherd Preaching Award and the Disciples Seminary Foundation Award. Pastor Lori has more than 25 years of experience in the administration and development of community, family, and social service programs. Pastor Lori, who was born on the border of Arizona and Mexico, is proud of her Mexican American culture and has worked bi-nationally to create healthy borders and develop programs to improve the quality of life in the areas of health, youth and families.',
    'speaker_title_4' => 'Missing Pieces: The Latino, Inmigrant, Trauma, Identity and the Church Workshop',
    'speaker_desc_4' => 'Dr. Harris holds a bachelor´s degree in psychology from the University of California, Irvine, as well as a master´s degree and doctorate in clinical psychology from Washington State University. Following a clinical internship at UCLA, he pursued postdoctoral work at Cornell University. Dr. Harris is a clinical fellow and formerly served as Program Officer for the American Psychological Association´s Minority Scholarship Program. In this capacity, he managed and wrote grants from various federal agencies, including NIMH, NIA, SAMHSA, CSAP, CSAT, and others. He is also an accomplished grant writer for foundations, having secured more than a dozen grants from major organizations like the Lilly Endowment, Kern Family Foundation, Oddo Foundation, and Lopez Foundation.
    Dr. Harris has held tenured faculty positions at Vanguard University and Bethany University, in addition to teaching and serving as adjunct faculty at institutions such as Washington State University, Pepperdine University, and UCI School of Medicine. He maintains a pastoral counseling practice, offering complimentary services to pastors and their families. Over the past six years, Dr. Harris has been a member of the Assemblies of God National Mental Health Committee (2018-present) and has served as an adjunct professor at Azusa Pacific Seminary for the past decade, focusing on mental health training for pastors and church leaders. An ordained minister of the Assemblies of God, Dr. Harris also holds positions as COA Commissioner of ABHE and President/CEO of LABI College in La Puente, California.',
    'speaker_title_5' => 'Identity and Preaching Workshop',
    'speaker_desc_5' => 'Rev. Dr. David Vásquez-Levy serves as President of Pacific School of Religion in Berkeley, California –a seminary and center for social justice that prepares spiritually rooted leaders to create a world where all can thrive.  A committed pastor, nationally recognized leader, and a sought after speaker, he leads at the intersection of faith, higher education, and social change. Born and raised in a Christian-Jewish household in Guatemala, he has lived in four countries. His experience, research, and passion guide his work with those “on the move”: congregations in transition, students discerning their callings, and immigrants. 
    He co-founded La Colectiva, a group of Latino/a executive leaders at ATS schools, and is a member of the executive leaders group of AshokaU campus network.  He also serves on the board of the Graduate Theological Union and is Chair of the board of Church World Service, one of the largest ecumenical development agencies in the world.  Vásquez-Levy regularly contributes a faith perspective to the national conversation on immigration, including speaking at a congressional briefing, immigration consultations with the both the Obama and the Biden White House, engaging in a series of public conversation with various State Attorneys across the country in an effort to reframe our national conversation about immigration.  He has consulted on a number of documentaries on immigration, labor, and human rights and is the author of various publications that explore migration stories in sacred texts and in people´s lives. ',
    'speaker_title_6' => 'Identity and Pastoral Advocacy Workshop',
    'speaker_desc_6' => 'Guesnerth Josué Perea is Executive Director of the afrolatin@ forum, Co-Curator of the AfoLatine Theology Project, Executive Producer of the documentary "Faith in Blackness: An Exploration of AfroLatine Spirituality", and Co-Host of the podcast "Majestad Prieta". His writings on AfroLatinidad have been part of various publications including Let Spirit Speak! Cultural Journeys through the African Diaspora, the Revista de Estudios Colombianos, and most recently Engaging Religion, a digital journal by Indiana University. Josué was once named by the newspaper amNewYork as one of five Colombians "making a mark" in New York City. ',
    'speaker_title_7' => 'Young Lideres and Identity Workshop',
    'speaker_desc_7' => 'Dr. Wilmer Estrada Carrasquillo, a native Puerto Rican, is the E. Stanley Jones Associate Professor of Evangelism at the Asbury Theological Seminary. Wilmer not only brings his experience in higher education but has also served the church as pastor and administrator.
Wilmer has written two books: Hacia una eclesiología Hispana-Latina: Una respuesta a la McDonaldización (Center for Latino Studies Press, 2018) and Beyond the Temple: Pentecostal Spirituality as a Lived Ecclesiology (CPT Press: Cleveland, TN. Book, 2021). Both monographs look at the church’s public presence and her calling to embody the gospel in its contexts. Furthermore, he co-authored The Church and Migration with Daniel Montañez, published journal articles, encyclopedia entries, and book chapters on Pentecostal spirituality, mission and evangelism, the intersection between faith and culture, Latina Theology, and the relationship between Pentecostalism and the Wesleyan movement.
Wilmer lives in Cleveland, TN, with Laura and their three daughters –Kalani, Mía, and Valeria, and their son, Anthony.',
    'speaker_title_8' => 'Identity and Migration Workshop',
    'speaker_desc_8' => 'Dr. Oscar Garcia-Johnson is a renowned scholar, experienced pastoral leader and innovator in indigenous theological education focused on millennials and indigenous and emerging communities in the Global South. His outstanding track record includes key roles as CEO of Diversity, Equity and Inclusion (2021-2023) and Academic Dean of the Center for the Study of the Hispanic Church and Community (2015-2021) at Fuller Theological Seminary. With 25 years of teaching experience, he currently enriches the Fuller Seminary community as Professor of Theology and Decolonial Studies.',
    'speaker_desc_8a' =>
        'Dr. García-Johnson´s varied educational background includes a Doctorate in Philosophical Theology and a Masters in Biblical Studies from Fuller Seminary, a B.A. in Philosophy and Religion from the University of La Verne, advanced studies in Electrical Engineering from the National Autonomous University of Honduras, and courses in Mortgage Banking (USA). A native of Honduras and based in the U.S. for over thirty years, Dr. Garcia-Johnson positions himself as a scholar of the Latino diaspora. And from that cross-border identity he forges his theological, cross-cultural, missional and interstate perspectives. His influential works include the new seven-volume series “New World Theology” (CLIE 2022 -) and incisive explorations of decolonial epistemologies and transwestern hermeneutics in Spirit Outside the Gate (IVP Academic 2019), Theology Without Borders (co-writer, BakerAcademic 2015) and Theological Conversations from the American Global South (co-editor, Open Doors/Wipf & Stock, 2016). His proposal for a Spirit-rooted transnational practical theology for the urban pastor in The Mestizo/a Community of the Spirit (Pickwick/Wipf&Stock 2009) continues to provide a basis for ecclesial imagination from the margins in the Global North.',
    'speaker_desc_8b' => 'Beyond the academy, Dr. Garcia-Johnson draws on his extensive experience in denominational leadership and church planting to provide insightful perspectives on the dynamics of contemporary multilingual and cross-cultural ministry. His international collaborations have advanced theological education in Latin America, Africa, the Middle East, Asia and the United States.',
    'speaker_desc_8c' => 'As a manager of decolonial approaches, Dr. Garcia-Johnson fosters an enriched, intergenerational learning environment that embraces emerging leadership insights and promotes provocative, de-victimizing and holistic theological discourse.',
    'speaker_title_9' => 'Trauma Keynote Speaker / Oradora Principal en Trauma',
    'speaker_desc_9' => 'Rev. Dr. Alma Tinoco Ruiz is a scholar, pastor, and educator dedicated to the fields of homiletics, evangelism, and Hispanic/Latino ministry. She is passionate about theological education, justice advocacy, and the intersection of preaching, pastoral care, and evangelism.',
    'speaker_desc_9a' => 'Rev. Dr. Tinoco Ruiz is a practical theologian whose work centers on the intersection of homiletics, pastoral care, and evangelism. Throughout her ministry, she has witnessed that most preachers are poorly equipped to respond to the traumatic injuries marginalized and oppressed communities experience. In contrast, she sees in the sermons of Saint Óscar Romero a profound response to the traumatic injuries the marginalized and oppressed people of El Salvador were experiencing during the years he was the archbishop of San Salvador (1977-1980). Influenced by Saint Romero’s preaching, Professor Tinoco Ruiz is exploring how preachers can effectively address the trauma experienced by marginalized and oppressed communities, particularly the community of undocumented immigrants from Latin America in the United States. She completed her Th.D. thesis on "Óscar Romero`s Theological, Hermeneutical, and Pastoral Framework for Preaching to Traumatized Communities." Her publications include essays in the International Journal of Homiletics, Predicación con Impacto: Preparación y Presentación de Mensajes Bíblicos, The Christian Century, and Duke Divinity School’s DIVINITY magazine. Professor Tinoco Ruiz was awarded the Denman Fellow of the Foundation for Evangelism (FFE) in 2016, the Forum for Theological Exploration (FTE) Doctoral Fellowship in 2019, and the Hispanic Theological Initiative (HTI)/Lilly fellowship in 2020. She is an ordained elder in the United Methodist Church.',
    'speaker_title_harold' => 'Baptist pastor, Theologian, and Business Administrator',
    'speaker_desc_harold' => 'Dr. Harold Segura is Colombian and the Director of the Faith and Development Department of World Vision for Latin America and the Caribbean. He is a university professor and theological instructor. He is a former rector of the International Baptist Theological Seminary (now the Baptist University Foundation). He graduated from the doctoral program in theology at the Pontifical Javeriana University of Colombia and from the National University of Costa Rica, where he is a doctoral candidate in the Faculty of Philosophy.He is an author of books on Christian spirituality, theology of childhood, and church leadership and mission. His latest books include "Theology in Times of TikTok," published by e625 (co-written with Pentecostal pastor Daniel Rebolledo), "The Gospel in a Few Words" (published by CLIE), and "Brushstrokes of the Gospel," published by the Bible Society of Spain.',
    'speaker_title_yenny' => 'Women and Trauma Workshop',
    'speaker_desc_yenny' => 'Yenny Delgado is a Ph.D. candidate in the Psychology of Religion at the University of Lausanne, Switzerland. A passionate scholar and activist committed to promoting decolonial, liberating, and feminist/womanist theology. Born in Perú, she has dedicated her professional life to research, education, and social action in various countries across the continent.
With a solid academic background, Yenny has earned multiple degrees spanning psychology, theology, and development cooperation. She holds a Licentiate degree in Psychology from Federico Villarreal University in Peru, a Licentiate degree in Theology from the Latin American Biblical University in Costa Rica, a Master`s degree in Development Cooperation from Jaume I University in Spain, and a Master`s degree in Public Theology from Wesley Theological Seminary in the United States. 
In addition to her academic trajectory, Yenny is an active religious leader, ordained ruling elder, and member of the Advisory Committee on Social Witness Policy in the Presbyterian Church, USA. Her commitment to social justice and inclusion is reflected in her work with social movements, local churches, and regional governments to promote inclusive and liberating education.
As the founder and director of Publica Theology, Yenny fosters a space that encourages dialogue and reflection on a theology committed to decolonization, liberation, and feminism/ womanism. Furthermore, since 2020, she has served as the convener coordinator of Women Doing Theology in Abya Yala, an ecumenical, intergenerational, and activist space that seeks to strengthen women`s presence and participation in theological education on the continent
Yenny Delgado`s work represents a significant contribution to constructing a contextualized theology committed to the realities and struggles of Abya Yala  communities, especially regarding gender equity and social justice.',
    'speaker_title_pablo' => 'Trauma and Bible Institutes Workshop ',
    'speaker_desc_pablo' => 'Pablo Anabalon is executive director of Los Angeles’s central region, West Valley and Asian Pacific Family Center divisions. With over 25 years of experience, Anabalon has held various roles at Pacific Clinics, including divisional director, program director and clinician. Additionally, he has led various internal committees to improve employee experiences and clinical outcomes, including Latino Services, Remote Work Project, Substance Use Disorder Committee and Cultural Competency Training Curriculum.
Anabalon is a licensed psychologist with a bachelor’s degree from Universidad de Chile and a PhD from Biola University. Anabalon completed his residency internship at Boston University/Boston Medical Center.',
    'speaker_title_andrea' => 'Trauma and Young Lideres Workshop',
    'speaker_desc_andrea' => 'Dr. Andrea Kauffman Canales, originally from Kailua-Kona, Hawaii, has been in pastoral leadership for the last 20 years among the Latina community in the greater Los Angeles area. Presently, she is in pastoral leadership at La Fuente Ministries in Pasadena. Dr. Canales earned her PhD in Clinical Psychology with a focus on family dynamics, trauma, resilience, and grief processes from the Graduate School of Psychology at Fuller Theological Seminary. She also holds an M.A. in Family Studies with an emphasis in Children at Risk, an M.A. in Intercultural Studies, and an M.A. in Psychology from Fuller. As a therapist she has worked extensively with clients from diverse backgrounds at Azusa Pacific University, City of Hope, Huntington Hospital, Child and Family Guidance Center, and Fuller Psychological and Family Services. Currently Dr. Canales works as a Licensed Clinical Psychologist at Relate Therapy Center working with couples, individuals, youth, and children in both Spanish and English with a focus on complex trauma, systemic factors, cultural context, and relational growth. Dr. Canales is also an Affiliate Faculty at Fuller Theological Seminary. She has taught courses in both the School of Psychology and Marriage and Family Therapy and the School of Mission and Theology. Her research expertise is in the areas of resilience, trauma, complicated grief processes, and spiritual and cultural integration.',
    'speaker_title_zareth' => 'Pastoral Advocacy and Trauma Workshop',
    'speaker_desc_zareth' => 'Rev. Alexandra Zareth is a child of God, a marriage and family therapist, and a board-certified chaplain by the Association of Professional Chaplains committed to the reconciliation of people to themselves through intentionally holistic concepts. As a lifelong learner, Alexandra’s studies have focused on human psychology, practical theology, clinical pastoral education, public policy, and international advocacy relations. Originally from Matamoros, Mexico, she directs a nonprofit, non-governmental organization dedicated to healing, educating, and empowering women. Alexandra maintains a private therapy practice, teaches pastoral care courses at multiple ATS-accredited institutions, and actively engages in international dialogue that bridges research and praxis. Additionally, she curates reflective retreat experiences designed to foster self-awareness and encourage a thriving, authentic existence.',
    'speaker_title_salvatierra' => 'Trauma and Migration Workshop',
    'speaker_desc_salvatierra' => 'Rev. Dr. Alexia Salvatierra is the Academic Dean of the Centro Latino and the Associate Professor of Mission and Global Transformation in Fuller Theological Seminary.  She is a specialist in the area of migration studies and has served in immigrant ministries, as well as in the founding and management of collaborative programs involving the Church in the pursuit of immigrant justice for more than 40 years.',
];