<?php
return [
    'speaker_title_1' => 'Orador Principal en Identidad',
    'speaker_desc_1' => 'Nació y creció en Cuba. En 1957 fue ordenado ministro de la Iglesia Metodista y en 1961 se convirtió en la persona más joven en obtener un doctorado en historia teológica de la Universidad de Yale. Durante treinta años el Dr. González enseñó en diversas instituciones teológicas, comenzando con ocho años en el Seminario Evangélico de Puerto Rico (1961-1969). Ha dado cientos de conferencias en Norteamérica, Sudamérica, Europa y Asia. También ha escrito más de cien libros, quizás los más conocidos sean su conjunto de dos volúmenes, Historia del cristianismo, y sus tres volúmenes, Historia del pensamiento cristiano, que han sido traducidos a ocho idiomas. Después de retirarse de la enseñanza a tiempo completo (1977) y del ministerio (1992), ha dedicado su tiempo a investigar, escribir y promover la educación teológica hispana. Como parte de este último, el Dr. González participó en la fundación de la Asociación para la Educación Teológica Hispana (AETH), la Iniciativa Teológica Hispana (HTI) y el Programa de Verano Hispano (HSP). La actividad que más valora y aprecia es asesorar y alentar a latinas, latinos y otros estudiantes minoritarios.',
    'speaker_title_2' => 'Tallerista en Identidad ',
    'speaker_desc_2' => 'El reverendo Dr. Robert Chao Romero es «asiático-latino» y, desde 2005, profesor de Estudios Chicanos y Asiático-Americanos en la UCLA.  Es doctor en Historia Latinoamericana por la UCLA y en Derecho por la Universidad de California en Berkeley. Romero ha publicado más de 30 libros y artículos académicos sobre cuestiones de raza, inmigración, historia, educación y religión, y ha recibido el premio Latina/o Studies book award de la Asociación Internacional de Estudios Latinoamericanos. Su libro más reciente, "Brown Church: Five Centuries of Latina/o Social Justice, Theology, and Identity (2020)", recibió el premio InterVarsity Press Readers´ Choice Award al mejor título académico.  Romero fue becario postdoctoral de la Fundación Ford y del Presidente de la Universidad de California, así como beneficiario de la Beca Sabática para Investigadores del Instituto Louisville.  Robert es también ministro ordenado y organizador comunitario.',
    'speaker_title_3' => 'Tallerista en Identidad y La Mujer ',
    'speaker_desc_3' => 'Pastora Nacional para Ministerios Hispanos de la Iglesia Cristiana (Discípulos de Cristo), es la primera mujer elegida a este cargo. Además, la Pastora Lori es plantadora de iglesias, autora, oradora y motivadora. La Pastora Tapia sirve con una pasión por compartir a Jesús de manera relevante, por empoderar a otros ayudándoles a crecer en su llamado y propósito, y por construir y mantener relaciones sólidas, auténticas y fieles que avanzan el reino entre nosotros. Profundamente arraigada en su ser es la adoración a través de la música como cantautora y adoradora. La Rev. Tapia recibió su Maestría en Divinidad de Claremont School of Theology, y fue otorgada con el Premio a la Predicación de la Iglesia del Buen Pastor y el Premio de la Fundación del Seminario de Discípulos. La Pastora cuenta con más de 25 años de experiencia en la administración y desarrollo de programas comunitarios, familiares, y de servicios sociales. La Pastora Lori, quien nació en la frontera de Arizona y México, es orgullosa de su cultura México Americana y ha trabajado a nivel binacional para crear fronteras saludables y desarrollar programas mejorando la calidad de vida en áreas de salud, jóvenes y familias.',
    'speaker_title_4' => 'Tallerista en Piezas perdidas: El latino, el inmigrante, el trauma, la identidad y la Iglesia.',
    'speaker_desc_4' => 'El Dr. Harris tiene una licenciatura en psicología de la Universidad de California, Irvine, así como una maestría y un doctorado en psicología clínica de la Universidad Estatal de Washington. Después de completar una pasantía clínica en la UCLA, realizó estudios posdoctorales en la Universidad de Cornell. El Dr. Harris es miembro clínico y anteriormente se desempeñó como Oficial del Programa de Becas para Minorías de la Asociación Estadounidense de Psicología. En este cargo, gestionó y redactó subvenciones de varias agencias federales, incluyendo el NIMH, NIA, SAMHSA, CSAP, CSAT, entre otras. También es un exitoso redactor de subvenciones para fundaciones, habiendo obtenido más de una docena de subvenciones de organizaciones importantes como la Fundación Lilly, la Fundación de la Familia Kern, la Fundación Oddo y la Fundación López.
El Dr. Harris ha ocupado cargos docentes con permanencia en la Universidad Vanguard y la Universidad Bethany, además de enseñar y ser profesor adjunto en instituciones como la Universidad Estatal de Washington, la Universidad Pepperdine y la Facultad de Medicina de la UCI. Mantiene una práctica de consejería pastoral, ofreciendo servicios gratuitos a pastores y sus familias. Durante los últimos seis años, el Dr. Harris ha sido miembro del Comité Nacional de Salud Mental de las Asambleas de Dios (2018-presente) y ha sido profesor adjunto en el Seminario Azusa Pacific durante la última década, enfocándose en la formación en salud mental para pastores y líderes eclesiásticos. Ordenado ministro de las Asambleas de Dios, el Dr. Harris también ocupa los cargos de Comisionado COA de ABHE y Presidente/Director Ejecutivo del LABI College en La Puente, California.',
    'speaker_title_5' => 'Tallerista Identidad y la predicación',
    'speaker_desc_5' => 'El Rev. Dr. David Vásquez-Levy es Presidente del seminario y centro de liderazgo Pacific School of Religion (PSR), localizado en Berkeley, California. Él es un pastor comprometido, un líder reconocido a nivel nacional y un orador bien solicitado. El liderazgo del Dr. Vásquez-Levy ha sido forjado en la intersección de la fe, la educación superior y el cambio social, guiando su trabajo en la preparación de líderes teológicos y espiritualmente arraigados para la transformación social. Creció en Guatemala en un hogar interreligioso, judío y cristiano, y ha vivido, estudiado y trabajado en cuatro países. Por su propia experiencia, trabajo académico y vocación religiosa, le apasiona servir con aquellos que están “en movimiento”: congregaciones en transición, estudiantes que disciernen y viven sus llamados, así como migrantes. 

Fue uno de los fundadores de La Colectiva, un grupo de ejecutivos Hispanos de la Asociación de Escuelas Teológicas (ATS), y es un miembro del grupo ejecutivo de la red de universidades de AshokaU. También es presidente de la junta de Church World Service, uno de los programas ecuménicos de desarrollo global y migración más grandes del mundo, y miembro de la junta directiva de la Unión Graduada Teológica (GTU). Vásquez-Levy contribuye regularmente una perspectiva de fe a la conversación nacional sobre inmigración, incluyendo hablar en una sesión informativa del Congreso de Estados Unidos, consultas de inmigración con la Casa Blanca de Obama y Biden, participar en una serie de conversaciones públicas con varios fiscales estatales en un esfuerzo por replantear nuestra conversación nacional sobre inmigración.  Ha trabajado como consultor en varios documentales sobre inmigración, trabajo y derechos humanos y es autor de varias publicaciones que exploran historias de migración en textos sagrados y en la vida de las personas.',
    'speaker_title_6' => 'Tallerista Identidad y Acompañamiento Pastoral',
    'speaker_desc_6' => 'Guesnerth Josué Perea es Director Ejecutivo del foro afrolatin@, Co-Curador del Proyecto de Teología Afrolatina, Productor Ejecutivo del documental "Faith in Blackness: An Exploration of AfroLatine Spirituality", y copresentador del podcast "Majestad Prieta". Sus escritos sobre la AfroLatinidad han formado parte de varias publicaciones, entre las que se incluyen ¡Dejad Hablar al Espíritu! Cultural Journeys through the African Diaspora, la Revista de Estudios Colombianos, y más recientemente Engaging Religion, una revista digital de la Universidad de Indiana. Josué fue nombrado en una ocasión por el periódico amNewYork como uno de los cinco colombianos que "dejan huella" en la ciudad de Nueva York.',
    'speaker_title_7' => 'Tallerista Identidad y Young Lideres',
    'speaker_desc_7' => 'El Dr. Wilmer Estrada Carrasquillo, oriundo de Puerto Rico, es profesor asociado de evangelismo E. Stanley Jones en el Seminario Teológico de Asbury. Wilmer no solo aporta su experiencia en educación superior, sino que también ha servido a la iglesia como pastor y administrador.


Wilmer ha escrito dos libros: Hacia una eclesiología hispano-latina: Una respuesta a la McDonaldización (Center for Latino Studies Press, 2018) y Beyond the Temple: Pentecostal Spirituality as a Lived Ecclesiology (CPT Press: Cleveland, TN. Book, 2021). Ambas monografías analizan la presencia pública de la iglesia y su llamado a encarnar el evangelio en sus contextos. Además, fue coautor de The Church and Migration con Daniel Montañez, publicó artículos de revistas, entradas de enciclopedias y capítulos de libros sobre espiritualidad pentecostal, misión y evangelización, la intersección entre fe y cultura, teología latina y la relación entre el pentecostalismo y el movimiento wesleyano.


Wilmer vive en Cleveland, Tennessee, con Laura y sus tres hijas: Kalani, Mía y Valeria, y su hijo, Anthony.',
    'speaker_title_8' => 'Tallerista Identidad y Migración ',
    'speaker_desc_8' => 'El Dr. Oscar García-Johnson es un reconocido académico, experimentado líder pastoral e innovador en la educación teológica autóctona enfocada en los mileniales y las comunidades indígenas y emergentes del Sur Global. Su destacado historial incluye roles clave como director general de Diversidad, Equidad e Inclusión (2021-2023) y Decano Académico del Centro para el Estudio de la Iglesia y Comunidad Hispana (2015-2021) del Seminario Teológico Fuller. Con una experiencia docente de 25 años, en la actualidad, enriquece la comunidad del Seminario Fuller como Profesor de Teología y Estudios Decoloniales.',
    'speaker_desc_8a' => 'La variada formación educativa del Dr. García-Johnson abarca un Doctorado Filosófico en Teología y una Maestría en Estudios Bíblicos del Seminario Fuller, una licenciatura en Filosofía y Religión de la Universidad de La Verne, estudios avanzados de Ingeniería Eléctrica de la Universidad Nacional Autónoma de Honduras y cursos de Banca Hipotecaria (USA). Oriundo de Honduras y ubicado en EE.UU. por más de treinta años, el Dr. García-Johnson se auto-posiciona como erudito de la diáspora latina. Y desde esa identidad transfronteriza forja sus perspectivas teológicas, interculturales, misionales e interestatales. Sus obras influyentes incluyen la nueva serie de siete volúmenes "Teología del Nuevo Mundo" (CLIE 2022 —) y exploraciones incisivas de epistemologías decoloniales y hermenéutica transoccidental en Spirit Outside the Gate (IVP Academic 2019), Theology Without Borders (co-escritor, Baker Academic 2015) y Conversaciones Teológicas del Sur Global Americano (co-editor, Puertas Abiertas/Wipf & Stock, 2016). Su propuesta de una teología práctica transnacional arraigada en el Espíritu para el pastor urbano en The Mestizo/a Community of the Spirit (Pickwick/Wipf & Stock 2009) continúa proporcionando una base para la imaginación eclesial desde los márgenes en el Norte Global.',
    'speaker_desc_8b' => 'Más allá de la academia, el Dr. García-Johnson aprovecha su amplia experiencia en liderazgo denominacional y plantación de iglesias para brindar perspicaces perspectivas sobre la dinámica del ministerio multilingüe e intercultural contemporáneo. Sus colaboraciones internacionales han avanzado en la educación teológica en América Latina, África, el Oriente Medio, Asia y los Estados Unidos.',
    'speaker_desc_8c' => 'Como gestor de enfoques decoloniales, el Dr. García-Johnson fomenta un entorno de aprendizaje enriquecido e intergeneracional que abraza las perspicacias del liderazgo emergente y promueve un discurso teológico provocador, desvictimizante e integral.',
    'speaker_title_9' => 'Oradora Principal en Trauma',
    'speaker_desc_9' => 'La Rev. Dra. Alma Tinoco Ruiz es una académica, pastora y educadora dedicada a los campos de la homilética, la evangelización y el ministerio hispano/latino. Su pasión abarca la educación teológica, la defensa de la justicia y la intersección entre la predicación, el cuidado pastoral y la evangelización.',
    'speaker_desc_9a' => 'La Rev. Dra. Tinoco Ruiz es una teóloga práctica cuyo trabajo se centra en la intersección entre la homilética, el cuidado pastoral y la evangelización. A lo largo de su ministerio, ha observado que la mayoría de los predicadores no están adecuadamente equipados para responder a las heridas traumáticas que sufren las comunidades marginadas y oprimidas. En contraste, encuentra en los sermones de San Óscar Romero una respuesta profunda a las heridas traumáticas vividas por el pueblo marginado y oprimido de El Salvador durante los años en que fue arzobispo de San Salvador (1977–1980). Influenciada por la predicación de San Romero, la profesora Tinoco Ruiz explora cómo los predicadores pueden abordar eficazmente el trauma experimentado por comunidades marginadas y oprimidas, en particular la comunidad de inmigrantes indocumentados de América Latina en los Estados Unidos. Completó su tesis de doctorado titulada: "El marco teológico, hermenéutico y pastoral de Óscar Romero para predicar a comunidades traumatizadas."
Sus publicaciones incluyen ensayos en el International Journal of Homiletics, Predicación con Impacto: Preparación y Presentación de Mensajes Bíblicos, The Christian Century y la revista DIVINITY de Duke Divinity School. La profesora Tinoco Ruiz recibió el reconocimiento Denman Fellow de la Foundation for Evangelism (FFE) en 2016, la beca doctoral del Forum for Theological Exploration (FTE) en 2019, y la beca de la Hispanic Theological Initiative (HTI)/Lilly en 2020. Es ministra ordenada de la Iglesia Metodista Unida.',
    'speaker_title_harold' => 'Taller Trauma y La Niñez',
    'speaker_desc_harold' => 'Dr. Harold Segura es colombiano y Director del Departamento de Fe y Desarrollo de World Vision para América Latina y El Caribe.  Profesor universitario y docente teológico. Ex-rector del Seminario Teológico Bautista Internacional (hoy Fundación Universitaria Bautista). Egresado del programa doctoral en teología de la Pontificia Universidad Javeriana de Colombia y de la Universidad Nacional de Costa Rica, donde es candidato al doctorado en la Facultad de Filosofía.

Escritor de libros sobre espiritualidad cristiana, teología de la niñez y liderazgo y misión de la iglesia. Últimos libros: Teología en tiempos de TikTok, editorial e625 (escrito junto con el pastor pentecostal Daniel Rebolledo), El Evangelio en pocas palabras (Editorial CLIE) y Pinceladas del Evangelio, Sociedad Bíblica de España).',
    'speaker_title_yenny' => 'Taller La Mujer y el Trauma',
    'speaker_desc_yenny' => 'Yenny Delgado es candidata a doctorado en Psicología de la Religión en la Universidad de Lausana, Suiza. Es una apasionada académica y activista comprometida con la promoción de una teología decolonial, liberadora y feminista/mujerista. Nacida en Perú, ha dedicado su vida profesional a la investigación, la educación y la acción social en diversos países del continente.
Con una sólida formación académica, Yenny ha obtenido múltiples titulaciones que abarcan áreas como la psicología, la teología y la cooperación para el desarrollo. Posee una licenciatura en Psicología por la Universidad Federico Villarreal en Perú, una licenciatura en Teología por la Universidad Bíblica Latinoamericana de Costa Rica, una maestría en Cooperación para el Desarrollo de la Universidad Jaume I en España, y una maestría en Teología Pública del Seminario Teológico Wesley en Estados Unidos. 

Además de su trayectoria académica, Yenny es una líder religiosa activa, siendo anciana gobernante ordenada y formando parte del Comité Asesor sobre Política de Testimonio Social en la Iglesia Presbiteriana de Estados Unidos. Su compromiso con la justicia social y la inclusión se refleja en su trabajo con movimientos sociales, iglesias locales y gobiernos regionales en la promoción de una educación inclusiva y liberadora.

Como fundadora y directora de Pública Theology, Yenny impulsa un espacio que fomenta el diálogo y la reflexión en torno a una teología comprometida con la descolonización, la liberación y el feminismo/mujerismo comunitario. Además, desde el 2020, se desempeña como coordinadora convocante de Mujeres Haciendo Teología en Abya Yala, un espacio ecuménico, intergeneracional y activista que busca fortalecer la presencia y participación de las mujeres en la educación teológica del continente.

El trabajo de Yenny Delgado representa un importante aporte a la construcción de una teología contextualizada y comprometida con las realidades y luchas de las comunidades originarias en Abya Yala, especialmente en lo que respecta a la equidad de género y la justicia social.',
    'speaker_title_pablo' => 'Taller Trauma e Institutos Biblicos',
    'speaker_desc_pablo' => 'Pablo Anabalon es director ejecutivo de las divisiones de la región central de Los Ángeles, West Valley y Asian Pacific Family Center. Con más de 25 años de experiencia, Anabalon ha desempeñado varios roles en Pacific Clinics, incluidos director de división, director de programas y médico. Además, ha liderado varios comités internos para mejorar las experiencias de los empleados y los resultados clínicos, incluidos los Servicios Latinos, el Proyecto de Trabajo Remoto, el Comité de Trastornos por Consumo de Sustancias y el Plan de Capacitación en Competencia Cultural. 

Anabalon es psicóloga licenciada, licenciada en la Universidad de Chile y doctorada en la Universidad de Biola. Anabalon completó su residencia en la Universidad de Boston/Centro Médico de Boston.',
    'speaker_title_andrea' => 'Trauma and Young Lideres Workshop',
    'speaker_desc_andrea' => 'La Dra. Drea Kauffman Canales, originaria de Kailua-Kona, Hawaii, ha estado en el liderazgo pastoral durante los últimos 20 años entre la comunidad latina en el área metropolitana de Los Ángeles. Actualmente, ejerce el liderazgo pastoral en La Fuente Ministries en Pasadena. La Dra. Canales obtuvo su doctorado en Psicología Clínica con un enfoque en dinámicas familiares, trauma, resiliencia y procesos de duelo en la Escuela de Psicología de Fuller Theological Seminary. También tiene una Maestría en Estudios Familiares con énfasis en Niños en Riesgo, una Maestría en Estudios Interculturales y una Maestría en Psicología de Fuller. Como terapeuta ha trabajado extensamente con clientes de diversos orígenes en Azusa Pacific University, City of Hope, Huntington Hospital, Child and Family Guidance Center, y Fuller Psychological and Family Services. Actualmente la Dra. Canales trabaja como Psicóloga Clínica Licenciada en Relate Therapy Center trabajando con parejas, individuos, jóvenes y niños tanto en español como en inglés con un enfoque en trauma complejo, factores sistémicos, contexto cultural y crecimiento relacional. La Dra. Canales es también Profesora Afiliada en el Seminario Teológico Fuller. Ha impartido cursos tanto en la Escuela de Psicología y Terapia Matrimonial y Familiar como en la Escuela de Misión y Teología. Su experiencia en investigación se centra en las áreas de resiliencia, trauma, procesos de duelo complicados e integración espiritual y cultural.',
    'speaker_title_zareth' => 'Pastoral Advocacy and Trauma Workshop',
    'speaker_desc_zareth' => 'La Reverenda Alexandra Zareth es hija de Dios, terapeuta familiar y matrimonial, y capellana certificada por la Asociación de Capellanes Profesionales, comprometida con la reconciliación de las personas consigo mismas a través de conceptos holísticos intencionales. Como estudiante de toda la vida, los estudios de Alexandra se han centrado en la psicología humana, la teología práctica, la educación pastoral clínica, las políticas públicas y las relaciones internacionales de abogacía. Originaria de Matamoros, México, dirige una organización no gubernamental sin fines de lucro dedicada a sanar, educar y empoderar a las mujeres. Alexandra tiene una consulta privada de terapia, imparte cursos de cuidado pastoral en varias instituciones acreditadas por la ATS y participa activamente en el diálogo internacional que tiende puentes entre la investigación y la praxis. Además, organiza retiros reflexivos diseñados para fomentar la conciencia de sí mismo y animar a llevar una existencia próspera y auténtica.
',
    'speaker_title_salvatierra' => 'Taller Trauma y Migración',
    'speaker_desc_salvatierra' => 'Es la Decana Académica del Centro Latino y la profesora asociada de Misión y Transformación Global en el Seminario Teológico Fuller.  Es especialista en estudios migratorios y ha servido en ministerios con inmigrantes, tanto como en la fundación y maneja de programas colaborativos involucrando a la Iglesia en la búsqueda de justicia en beneficio de los migrantes por más de 40 años.',
];

